### ISSUE TITLE
Overnight issue

### ISSUE THREAD

**Issue by wilokecom** [sbarry50/vue-business-hours#11]
Hi,

Some business like a bar will open from 6 AM to 3 AM (next day), but they can't do that because your plugin is preventing it  https://nimb.ws/8KjEpC Could you please improve this feature?
Thanks

**Comment by sbarry50** [comment]
In those types of overnight situations, since the days are technically changing at midnight, you would create an entry from opening time to midnight on the day it opens and then an entry from 12:00 am to the closing time on the next day. So if you're open from 6am to 3am on say a Friday. Then it's Friday 6am to midnight and Saturday 12:00am to 3:00am. 

I took these situations into consideration when I made it but it got very messy when I tried to work it any other way. If someone else can come up with a better solution that works, then I'm certainly open to looking at it but I already took a stab at myself and came up empty.
